name: test_laptopc

on:
  push:
    branches: [ "main" ]
    paths-ignore:
      - '*.md'
  pull_request:
    branches: [ "main" ]
    paths:
        - ".github/workflows/test_laptoppc_.yaml"

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python 3.12.3
        uses: actions/setup-python@v5
        with:
          python-version: 3.12.3

      - name: Confirm Python version
        run: python --version

      - name: Build-install blasfeo
        run: |
          git clone https://github.com/giaf/blasfeo.git
          cd blasfeo
          make shared_library -j 4 && sudo make install_shared

      - name: Build-install hpipm
        run: |
          git clone https://github.com/giaf/hpipm.git
          cd hpipm
          make shared_library -j 4 && sudo make install_shared
          cd interfaces/python/hpipm_python
          python setup.py install
          pwd
